[tool.poetry]
name = "lunch-and-learn"
version = "0.1.0"
description = ""
authors = ["Ben Chavez <ben.m.chavez@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyright = "^1.1.400"


[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
pyright = "^1.1.400"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
